In [1]:
import pandas as pd
import numpy as np 
import requests
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv(f"D:\Web Scrapping\project\Wemedgood\Funtions_data.csv")

In [3]:
df

,Name,Ratings,Reviews,Type,Location,Menu_price,PAX,Rooms,Amenities
0,Aurum Conventions and Resort Sohna Road Gurgaon,5.0,62 reviews,Hotel with Banquet & Lawn,"Sohna Road, Gurgaon","₹2,600per plate",60-2000,20.0,+6 more
1,Le Méridien New Delhi,NaN,24 reviews,Wedding Destination\t,"Central Delhi, Delhi NCR","₹5,500per plate",25-1000,358.0,+3 more
2,The Leela Palace New Delhi,4.8,21 reviews,Luxury City Center Hotel,"New Delhi, Delhi NCR","₹6,000per plate",25-300,254.0,+6 more
3,"Radisson Blu Hotel, New Delhi Dwarka",NaN,40 reviews,5 Star Hotel,"Dwarka, Delhi NCR","₹2,800per plate",35-800,240.0,+4 more
4,The Grand New Delhi,4.6,19 reviews,5 Star Hotel,"Vasant Kunj, Delhi NCR","₹4,000per plate",70-2000,382.0,+4 more
...,...,...,...,...,...,...,...,...,...
2995,Shree PL Vatika Marriage Garden,NaN,NaN,Lawn & Banquet Hall,Jaipur,"₹70,000per function",100-3000,NaN,+3 more
2996,Hotel Le Amour Inn,4.5,1 review,Banquet Hall,"Tonk Road, Jaipur",₹750per plate,90-200,27.0,+3 more
2997,Parshuram Garden,NaN,NaN,Wedding Lawn,"Vidhyadhar Nagar, Jaipur",₹400per plate,600-1500,NaN,+2 more
2998,Karma Rooftop Lounge,NaN,NaN,Banquet Hall & Lawn,"Raja Park, Jaipur",₹700per plate,70-100,NaN,+1 more
2999,Keshav Resort,NaN,NaN,Resort,Jaipur,₹800per plate,150-1000,30.0,+3 more

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        3000 non-null   object
 1   Ratings     1216 non-null   float64
 2   Reviews     1572 non-null   object
 3   Type        2983 non-null   object
 4   Location    3000 non-null   object
 5   Menu_price  3000 non-null   object
 6   PAX         3000 non-null   object
 7   Rooms       1574 non-null   float64
 8   Amenities   3000 non-null   object
dtypes: float64(2), object(7)
memory usage: 211.1+ KB

In [5]:
df.isna().sum()

Name             0
Ratings       1784
Reviews       1428
Type            17
Location         0
Menu_price       0
PAX              0
Rooms         1426
Amenities        0
dtype: int64

In [6]:
# extracting review 
df["Reviews"]= df["Reviews"].replace("[\D]","",regex=True)

In [7]:
df["Reviews"].isna().sum()

np.int64(1428)

In [8]:
# extracting menu_price 
df["Menu_price"]= df["Menu_price"].replace("[\D]","",regex=True)

In [9]:
df

,Name,Ratings,Reviews,Type,Location,Menu_price,PAX,Rooms,Amenities
0,Aurum Conventions and Resort Sohna Road Gurgaon,5.0,62,Hotel with Banquet & Lawn,"Sohna Road, Gurgaon",2600,60-2000,20.0,+6 more
1,Le Méridien New Delhi,NaN,24,Wedding Destination\t,"Central Delhi, Delhi NCR",5500,25-1000,358.0,+3 more
2,The Leela Palace New Delhi,4.8,21,Luxury City Center Hotel,"New Delhi, Delhi NCR",6000,25-300,254.0,+6 more
3,"Radisson Blu Hotel, New Delhi Dwarka",NaN,40,5 Star Hotel,"Dwarka, Delhi NCR",2800,35-800,240.0,+4 more
4,The Grand New Delhi,4.6,19,5 Star Hotel,"Vasant Kunj, Delhi NCR",4000,70-2000,382.0,+4 more
...,...,...,...,...,...,...,...,...,...
2995,Shree PL Vatika Marriage Garden,NaN,NaN,Lawn & Banquet Hall,Jaipur,70000,100-3000,NaN,+3 more
2996,Hotel Le Amour Inn,4.5,1,Banquet Hall,"Tonk Road, Jaipur",750,90-200,27.0,+3 more
2997,Parshuram Garden,NaN,NaN,Wedding Lawn,"Vidhyadhar Nagar, Jaipur",400,600-1500,NaN,+2 more
2998,Karma Rooftop Lounge,NaN,NaN,Banquet Hall & Lawn,"Raja Park, Jaipur",700,70-100,NaN,+1 more
2999,Keshav Resort,NaN,NaN,Resort,Jaipur,800,150-1000,30.0,+3 more

In [10]:
df["Menu_price"].isna().sum()

np.int64(0)

In [11]:
# Extracting min and max guest capacities from pax column
df[["Pax_Min", "Pax_Max"]] = df["PAX"].str.extract(r"(\d+)-(\d+)")

In [12]:
# converting name, type, and location column to lower case
df["Name"]= df["Name"].str.lower()
df["Type"]= df["Type"].str.lower()
df["Location"]= df["Location"].str.lower()

In [13]:
# extracting destination/ city name from the location column 

df["Destination"]= df["Location"].str.strip().str.split().str[-1]

In [14]:
# extracting only digits from amenities column
df["Amenities_+more"]= df["Amenities"].replace("[\D]","",regex=True)

In [15]:
# Drop Pax Column 
df.drop(df[["PAX"]], axis=1, inplace=True)

In [16]:
# Drop Location Column
df.drop(df[["Location"]], axis=1, inplace=True)

In [17]:
# Drop Amenities column
df.drop(df[["Amenities"]], axis=1, inplace=True)

In [18]:
df

,Name,Ratings,Reviews,Type,Menu_price,Rooms,Pax_Min,Pax_Max,Destination,Amenities_+more
0,aurum conventions and resort sohna road gurgaon,5.0,62,hotel with banquet & lawn,2600,20.0,60,2000,gurgaon,6
1,le méridien new delhi,NaN,24,wedding destination\t,5500,358.0,25,1000,ncr,3
2,the leela palace new delhi,4.8,21,luxury city center hotel,6000,254.0,25,300,ncr,6
3,"radisson blu hotel, new delhi dwarka",NaN,40,5 star hotel,2800,240.0,35,800,ncr,4
4,the grand new delhi,4.6,19,5 star hotel,4000,382.0,70,2000,ncr,4
...,...,...,...,...,...,...,...,...,...,...
2995,shree pl vatika marriage garden,NaN,NaN,lawn & banquet hall,70000,NaN,100,3000,jaipur,3
2996,hotel le amour inn,4.5,1,banquet hall,750,27.0,90,200,jaipur,3
2997,parshuram garden,NaN,NaN,wedding lawn,400,NaN,600,1500,jaipur,2
2998,karma rooftop lounge,NaN,NaN,banquet hall & lawn,700,NaN,70,100,jaipur,1
2999,keshav resort,NaN,NaN,resort,800,30.0,150,1000,jaipur,3

In [19]:
# Checking for the missing values
df.isna().sum()

Name                  0
Ratings            1784
Reviews            1428
Type                 17
Menu_price            0
Rooms              1426
Pax_Min               0
Pax_Max               0
Destination           0
Amenities_+more       0
dtype: int64

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             3000 non-null   object
 1   Ratings          1216 non-null   float64
 2   Reviews          1572 non-null   object
 3   Type             2983 non-null   object
 4   Menu_price       3000 non-null   object
 5   Rooms            1574 non-null   float64
 6   Pax_Min          3000 non-null   object
 7   Pax_Max          3000 non-null   object
 8   Destination      3000 non-null   object
 9   Amenities_+more  3000 non-null   object
dtypes: float64(2), object(8)
memory usage: 234.5+ KB

In [21]:
# converting pax min, pax maqx column to numeric 
# df["Pax_Max"]= pd.to_numeric(df["Pax_Max"])
# df["Pax_Min"]= pd.to_numeric(df["Pax_Min"])

In [22]:
df.isna().sum().sum()

np.int64(4655)

In [23]:
df

,Name,Ratings,Reviews,Type,Menu_price,Rooms,Pax_Min,Pax_Max,Destination,Amenities_+more
0,aurum conventions and resort sohna road gurgaon,5.0,62,hotel with banquet & lawn,2600,20.0,60,2000,gurgaon,6
1,le méridien new delhi,NaN,24,wedding destination\t,5500,358.0,25,1000,ncr,3
2,the leela palace new delhi,4.8,21,luxury city center hotel,6000,254.0,25,300,ncr,6
3,"radisson blu hotel, new delhi dwarka",NaN,40,5 star hotel,2800,240.0,35,800,ncr,4
4,the grand new delhi,4.6,19,5 star hotel,4000,382.0,70,2000,ncr,4
...,...,...,...,...,...,...,...,...,...,...
2995,shree pl vatika marriage garden,NaN,NaN,lawn & banquet hall,70000,NaN,100,3000,jaipur,3
2996,hotel le amour inn,4.5,1,banquet hall,750,27.0,90,200,jaipur,3
2997,parshuram garden,NaN,NaN,wedding lawn,400,NaN,600,1500,jaipur,2
2998,karma rooftop lounge,NaN,NaN,banquet hall & lawn,700,NaN,70,100,jaipur,1
2999,keshav resort,NaN,NaN,resort,800,30.0,150,1000,jaipur,3

In [24]:
# filling out missing valuees for each column 

df["Ratings"].fillna(df["Ratings"].median(), inplace=True)

df["Rooms"].fillna(df["Rooms"].median(), inplace=True)

df["Reviews"].fillna(0, inplace=True)

df["Type"].fillna(0, inplace=True)

df.dropna(subset=["Amenities_+more"], inplace=True)

In [25]:
df.isna().sum()

Name               0
Ratings            0
Reviews            0
Type               0
Menu_price         0
Rooms              0
Pax_Min            0
Pax_Max            0
Destination        0
Amenities_+more    0
dtype: int64

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             3000 non-null   object
 1   Ratings          3000 non-null   float64
 2   Reviews          3000 non-null   object
 3   Type             3000 non-null   object
 4   Menu_price       3000 non-null   object
 5   Rooms            3000 non-null   float64
 6   Pax_Min          3000 non-null   object
 7   Pax_Max          3000 non-null   object
 8   Destination      3000 non-null   object
 9   Amenities_+more  3000 non-null   object
dtypes: float64(2), object(8)
memory usage: 234.5+ KB

In [42]:
# now chaging data type for each feature according to its need

df["Reviews"]=df["Reviews"].astype(int)

df["Pax_Min"]= df["Pax_Min"].astype(float)
df["Pax_Max"] = df["Pax_Max"].astype(float)

df["Amenities_+more"]= df["Amenities_+more"].astype(int)

In [29]:
df.duplicated().sum()

np.int64(23)

In [30]:
# Dropping the Duplicate
df.drop_duplicates(inplace=True)

In [31]:
# checking duplicates
df.duplicated().sum()

np.int64(0)

In [32]:
df.describe()

           Ratings      Reviews        Rooms
count  2977.000000  2977.000000  2977.000000
mean      4.969499     2.729929    30.293248
std       0.101021     8.376291    42.721415
min       4.500000     0.000000     1.000000
25%       5.000000     0.000000    20.000000
50%       5.000000     1.000000    20.000000
75%       5.000000     2.000000    22.000000
max       5.000000   250.000000   461.000000

In [33]:
# Save the clean csv file
df.to_csv("Clean_FunctionData.csv", index=False)

In [34]:
df

,Name,Ratings,Reviews,Type,Menu_price,Rooms,Pax_Min,Pax_Max,Destination,Amenities_+more
0,aurum conventions and resort sohna road gurgaon,5.0,62,hotel with banquet & lawn,2600,20.0,60,2000,gurgaon,6
1,le méridien new delhi,5.0,24,wedding destination\t,5500,358.0,25,1000,ncr,3
2,the leela palace new delhi,4.8,21,luxury city center hotel,6000,254.0,25,300,ncr,6
3,"radisson blu hotel, new delhi dwarka",5.0,40,5 star hotel,2800,240.0,35,800,ncr,4
4,the grand new delhi,4.6,19,5 star hotel,4000,382.0,70,2000,ncr,4
...,...,...,...,...,...,...,...,...,...,...
2995,shree pl vatika marriage garden,5.0,0,lawn & banquet hall,70000,20.0,100,3000,jaipur,3
2996,hotel le amour inn,4.5,1,banquet hall,750,27.0,90,200,jaipur,3
2997,parshuram garden,5.0,0,wedding lawn,400,20.0,600,1500,jaipur,2
2998,karma rooftop lounge,5.0,0,banquet hall & lawn,700,20.0,70,100,jaipur,1
2999,keshav resort,5.0,0,resort,800,30.0,150,1000,jaipur,3

In [35]:
df["Menu_price"].unique()

array(['2600', '5500', '6000', '2800', '4000', '2500', '', '2200', '2000',
       '4450', '1750', '3450', '2750', '4500', '415', '250000', '1300',
       '650', '850', '375', '1450', '800', '80000', '650000', '750',
       '500000', '400', '4200', '2850', '1000000', '899', '1199', '1000',
       '649', '699', '1500', '1600', '1800', '600', '2899', '1050', '900',
       '1200', '950', '1900', '2100', '1400', '7000', '1999', '1100',
       '799', '1799', '3500', '1850', '3000', '999', '2300', '200',
       '3400', '300', '350', '45000', '125000', '1700', '275', '1444',
       '500', '2499', '460', '200000', '2700', '499', '1550', '85000',
       '9500000', '3300', '90000', '140000', '50000', '250', '240000',
       '599', '550', '60000', '100000', '120000', '150', '180000', '3200',
       '3700', '1350', '1575', '450', '1299', '301000', '1650', '69502',
       '75000', '525', '700', '1375', '330000', '150000', '350000',
       '1150', '1599', '1250', '2400', '400000', '104000', '475', '680',
       '160000', '2375', '65000', '1399', '5000', '3800', '1699', '25000',
       '300000', '600000', '40000', '175000', '3600', '2250', '975',
       '95000', '18000', '2550000', '849', '590', '35000', '360', '675',
       '575', '430', '10000', '51000', '369000', '30000', '8000', '2999',
       '265000', '390', '180', '1949', '800000', '6500', '42000',
       '190000', '225', '560', '740000', '425', '15000', '1600000',
       '3299', '890', '175', '280', '760', '579', '1099', '55000',
       '70000', '135000', '110000', '2050', '261000', '659', '1499',
       '130000', '240', '1275', '171000', '220', '20000', '3100', '446',
       '280000', '100', '445000', '695', '27000', '595', '420', '690',
       '11000', '251000', '32000', '750000', '2150', '815', '700000',
       '435', '225000', '151000', '1500000', '775', '230', '349', '325',
       '120', '666', '830', '549', '3799', '41000'], dtype=object)

In [36]:
df["Menu_price"] = pd.to_numeric(
    df["Menu_price"].str.replace(r"[^\d.]", "", regex=True),
    errors="coerce"
)

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2977 entries, 0 to 2999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             2977 non-null   object
 1   Ratings          2977 non-null   float64
 2   Reviews          2977 non-null   int64
 3   Type             2977 non-null   object
 4   Menu_price       2586 non-null   float64
 5   Rooms            2977 non-null   float64
 6   Pax_Min          2977 non-null   float64
 7   Pax_Max          2977 non-null   float64
 8   Destination      2977 non-null   object
 9   Amenities_+more  2977 non-null   int64
dtypes: float64(5), int64(2), object(3)
memory usage: 255.8+ KB